// <auto-generated />
using CityInfo.API.DbContexts;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CityInfo.API.Migrations
{
    [DbContext(typeof(CityInfoContext))]
    [Migration("20230307222033_fixCityEntityMigration")]
    partial class fixCityEntityMigration
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "6.0.0");

            modelBuilder.Entity("CityInfo.API.Entities.City", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Cities");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "The capital of France, A very european city",
                            Name = "Paris"
                        },
                        new
                        {
                            Id = 2,
                            Description = "The most populous city in the United States, known for its iconic skyline and cultural attractions",
                            Name = "New York City"
                        },
                        new
                        {
                            Id = 3,
                            Description = "The capital of England, known for its rich history, landmarks, and diverse culture",
                            Name = "London"
                        },
                        new
                        {
                            Id = 4,
                            Description = "The capital of Japan, known for its modern technology, vibrant nightlife, and traditional culture",
                            Name = "Tokyo"
                        },
                        new
                        {
                            Id = 5,
                            Description = "The largest city in Australia, known for its beaches, landmarks, and cosmopolitan lifestyle",
                            Name = "Sydney"
                        },
                        new
                        {
                            Id = 6,
                            Description = "A coastal city in Brazil, known for its natural beauty, cultural events, and Carnival celebration",
                            Name = "Rio de Janeiro"
                        });
                });

            modelBuilder.Entity("CityInfo.API.Entities.PointOfInterest", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("CityId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CityId");

                    b.ToTable("PointsOfInterest");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CityId = 1,
                            Description = "Tallest structure for 4 decades and a very known monument worldwide",
                            Name = "Eiffel Tower"
                        },
                        new
                        {
                            Id = 2,
                            CityId = 1,
                            Description = "One of the world's largest museums, home to many famous works of art including the Mona Lisa",
                            Name = "Louvre Museum"
                        },
                        new
                        {
                            Id = 3,
                            CityId = 1,
                            Description = "One of the most famous and luxurious avenues in the world, known for its high-end shops and cafes",
                            Name = "Champs-Élysées"
                        },
                        new
                        {
                            Id = 4,
                            CityId = 2,
                            Description = "A symbol of freedom and democracy, gifted to the United States by France in 1886",
                            Name = "Statue of Liberty"
                        },
                        new
                        {
                            Id = 5,
                            CityId = 2,
                            Description = "A massive park in the heart of Manhattan, featuring lakes, gardens, and various attractions",
                            Name = "Central Park"
                        },
                        new
                        {
                            Id = 6,
                            CityId = 2,
                            Description = "A famous Art Deco skyscraper that offers stunning views of the city from its observation deck",
                            Name = "Empire State Building"
                        },
                        new
                        {
                            Id = 7,
                            CityId = 3,
                            Description = "The nickname for the clock tower of the Palace of Westminster, a symbol of British democracy and culture",
                            Name = "Big Ben"
                        },
                        new
                        {
                            Id = 8,
                            CityId = 3,
                            Description = "A famous bridge over the River Thames, known for its distinctive towers and Victorian architecture",
                            Name = "Tower Bridge"
                        },
                        new
                        {
                            Id = 9,
                            CityId = 3,
                            Description = "One of the world's oldest and largest museums, with a vast collection of artifacts from around the globe",
                            Name = "British Museum"
                        },
                        new
                        {
                            Id = 10,
                            CityId = 4,
                            Description = "A broadcasting tower and observation deck, offering panoramic views of the city",
                            Name = "Tokyo Skytree"
                        },
                        new
                        {
                            Id = 11,
                            CityId = 4,
                            Description = "One of the busiest pedestrian intersections in the world, with up to 3,000 people crossing at once",
                            Name = "Shibuya Crossing"
                        },
                        new
                        {
                            Id = 12,
                            CityId = 4,
                            Description = "A Shinto shrine dedicated to Emperor Meiji and Empress Shoken, surrounded by a tranquil forest in the heart of Tokyo",
                            Name = "Meiji Shrine"
                        },
                        new
                        {
                            Id = 13,
                            CityId = 5,
                            Description = "A multi-venue performing arts center in Sydney, famous for its unique and iconic design",
                            Name = "Sydney Opera House"
                        },
                        new
                        {
                            Id = 14,
                            CityId = 5,
                            Description = "A steel arch bridge that spans the Sydney Harbour, known for its scenic views and being a popular site for adventure tourism",
                            Name = "Harbour Bridge"
                        },
                        new
                        {
                            Id = 15,
                            CityId = 5,
                            Description = "A popular beach and coastal suburb in Sydney, known for its turquoise waters, golden sands, and laid-back lifestyle",
                            Name = "Bondi Beach"
                        },
                        new
                        {
                            Id = 16,
                            CityId = 6,
                            Description = "A statue of Jesus Christ in Rio de Janeiro, one of the world's most famous and iconic religious monuments",
                            Name = "Christ the Redeemer"
                        },
                        new
                        {
                            Id = 17,
                            CityId = 6,
                            Description = "A long, crescent-shaped beach in Rio de Janeiro, famous for its golden sands and for its lively atmosphere, beach sports, and many beachfront bars and restaurants",
                            Name = "Copacabana Beach"
                        });
                });

            modelBuilder.Entity("CityInfo.API.Entities.PointOfInterest", b =>
                {
                    b.HasOne("CityInfo.API.Entities.City", "City")
                        .WithMany("PointsOfInterest")
                        .HasForeignKey("CityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("City");
                });

            modelBuilder.Entity("CityInfo.API.Entities.City", b =>
                {
                    b.Navigation("PointsOfInterest");
                });
#pragma warning restore 612, 618
        }
    }
}
